name: C++ Release

on:
  push:
    branches: [ "main" ]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      # 1. Клонируем репозиторий
      - uses: actions/checkout@v4

      # 2. Устанавливаем зависимости
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake g++

      # 3. Конфигурируем CMake
      - name: Configure
        run: |
          mkdir -p build
          cmake -S . -B build

      # 4. Собираем бинарник
      - name: Build
        run: cmake --build build

      # 5. Прогоняем md5 тест
      - name: Test
        run: |
          echo "Expected hash: 24e7a7b2270daee89c64d3ca5fb3da1a"
          RESULT=$(cat ./ip_filter.tsv | ./build/ip_filter | md5sum | awk '{print $1}')
          echo "Actual hash:   $RESULT"
          test "$RESULT" = "24e7a7b2270daee89c64d3ca5fb3da1a"

      # 6. Собираем .deb через CPack
      - name: Package
        run: |
          cd build
          cpack -G DEB

      # 7. Загружаем .deb на GitHub Release
      - name: Release .deb
        uses: softprops/action-gh-release@v1
        with:
          files: build/*.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


